### ISSUE TITLE
Minecraft Server Command starts the wrong server

### ISSUE THREAD

**Issue by Roxiun** [Roxiun/RoxBot#12]
Running the command `?mcserver start tst-smp` starts the bedwars server instead of the smp server.

**Comment by TheSavageTeddy** [comment]
yes please fix

also wdym low priority this is important smh
and also make the thing take 20s to load because it apparently needs longer time

**Comment by Roxiun** [comment]
> yes please fix
> 
> also wdym low priority this is important smh
> and also make the thing take 20s to load because it apparently needs longer time

1. Its only important to you guys not anyone else
2. Patching soon
